### ISSUE TITLE
Class 'X' with member that has list of X crashes virtual machine.

### ISSUE THREAD

**Issue by SanderMertens** [cortoproject/corto#3]
The following code:

```
class Recursive::
    x : list{Recursive,1};

Recursive o3: {o3};
var Recursive v3 = Recursive{{o3}};
```

Crashes the virtual machine and dumps the following information:

```
Access violation
[1] <main> (test.hyve:5)

  ...
  161300980: DEFINE_LV 0 0 161268684 0
  161301000: NEW_LRP 4 0 161229916 0
  161301020: PUSHANY_LQ 4 0 0 161267296
  161301040: PUSHANY_LV 0 0 161268684 161229916
> 161301060: DB_VM_CALLVOID 3077923404 
  161301080: DEFINE_LR 4 0 0 0
  161301100: SETREF_LRR 0 4 0 0
  161301120: FREE_LR 0 0 0 0
  161301140: FREE_LR 4 0 0 0
```

gdb shows that the crash is caused in this stack:

```
Program received signal SIGSEGV, Segmentation fault.
0xb7f381b5 in db_llAppend (list=0x0, data=0x807f400) at src/db_ll.c:131
131     db_llNode node = list->first;
(gdb) where
#0  0xb7f381b5 in db_llAppend (list=0x0, data=0x807f400) at src/db_ll.c:131
#1  0xb7f1dbfa in db_list_appendAction (list=0x0, value=0x807f400, userData=0x0) at src/db_collection.c:440
#2  0xb7f1da3b in db_list_do (object=..., element=..., insert=0 '\000', action=0xb7f1dbd0 <db_list_appendAction>, userData=0x0)
    at src/db_collection.c:428
#3  0xb7f1db1c in db_list_append (object=..., element=...) at src/db_collection.c:448
#4  0xb7f99d21 in db_call_cdecl_word () at db_cdecl_x86.s:37
#5  0xb7f1ae00 in db_call_cdecl (f=0xb7fb224c <list_append.o+68>, result=0x0, args=0xbfffac70) at src/db_cdecl.c:94
#6  0xb7f1ac97 in db_call_intern (f=0xb7fb224c <list_append.o+68>, result=0x0, args=0xbfffac70) at src/db_call.c:93
#7  0xb7f1ad11 in db_callb (f=0xb7fb224c <list_append.o+68>, result=0x0, args=0xbfffac70) at src/db_call.c:115
#8  0xb7f71aa0 in db_vm_run_w_storage (program=0x80857c8, reg=0xbfffe900, result=0x0) at src/db_vm.c:1419
#9  0xb7f57938 in db_vm_run (program=0x80857c8, result=0x0) at src/db_vm.c:1475
#10 0xb7c5de09 in Fast_Parser_toIc (_this=0x8074cb8) at src/Fast_Parser.c:169
#11 0xb7c64557 in Fast_Parser_parse (_this=0x8074cb8) at src/Fast_Parser.c:2269
#12 0xb7c2e014 in fast_hyveRun (file=0xbfffece4 "test.hyve", udata=0x0) at src/fastmain.c:34
#13 0xb7f38dc8 in db_load (str=0xbfffece4 "test.hyve") at src/db_loader.c:142
#14 0x08048769 in main (argc=2, argv=0xbfffef94) at src/hyve.c:32
```

**Comment by SanderMertens** [comment]
Issues with the scripting language are postponed.
