### ISSUE TITLE
enums are not generated correctly in the C binding

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#474]
At some point after a9eb6c5e6963c0b178521defe831004806b7cf84, the C binding stopped listing enum constants, producing an empty enum{} statement instead.

```
web$ rake
src/web.c
[ libweb.so ]
[ >> entering server ]
src/DDP.c
In file included from src/DDP.c:9:
In file included from /Users/JohnnyLee/.corto/include/corto/0.2/corto/web/server/server.h:10:
/Users/JohnnyLee/.corto/include/corto/0.2/corto/web/server/_type.h:144:1: error: use of empty enum
} server_HTTP_Method;
^
1 error generated.
corto: command failed: cc -c -Wall -fvisibility=hidden -std=c99 -Wstrict-prototypes -pedantic -fPIC -D_XOPEN_SOURCE=600 -g -O0 -fprofile-arcs -ftest-coverage -DBUILDING_CORTO_WEB_SERVER -DCORTO_WEB_SERVER_ETC='"/Users/JohnnyLee/.corto/etc/corto/0.2/corto/web/server"' -Isrc -I/Users/JohnnyLee/.corto/include/corto/0.2 -I/usr/local/include/corto/0.2 src/DDP.c -o .corto/obj/Darwin-x86_64/DDP.o
rake aborted!
Command failed with status (1): [rake -f server/rakefile...]
/Users/JohnnyLee/cortoproject/corto/build/subrake.rb:13:in `block (2 levels) in <top (required)>'
/Users/JohnnyLee/cortoproject/corto/build/subrake.rb:8:in `each'
/Users/JohnnyLee/cortoproject/corto/build/subrake.rb:8:in `block in <top (required)>'
Tasks: TOP => default
(See full trace by running task with --trace)
```

**Comment by jleeothon** [comment]
This was an issue of non-latest versions of c-binding and corto working together.
